version: '3.8'

services:
  bloglite:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./instance:/app/instance
      - ./applicaton/static/uploads:/app/applicaton/static/uploads
    environment:
      - FLASK_ENV=production
      - FLASK_APP=applicaton
      - FLASK_DEBUG=0
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=5000