name: Docker Build and Push

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build Docker image
      run: docker build -t bloglite:latest .
    - name: Run tests (optional)
      run: |
        # Add test commands if you have tests (e.g., pytest)
        echo "Running tests..."
    - name: Log in to Docker Hub
      if: github.event_name == 'push'
      run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
    - name: Push to Docker Hub
      if: github.event_name == 'push'
      run: |
        docker tag bloglite:latest colinpaulebby/bloglite:latest
        docker push colinpaulebby/bloglite:latest